// Auto-generated by scripts/extract-stack-icons.ts — do not edit.
// Source: tech-stack-icons (MIT) — https://tech-stack-icons.com
// Regenerate: bun run extract:stack-icons

export const SKILL_ICON_KEYS = [
  "react",
  "nextjs2",
  "typescript",
  "tailwindcss",
  "shadcnui",
  "zod",
  "git",
  "html5",
  "css3",
  "js",
  "prisma",
  "baseui",
  "docker",
  "cursor",
  "bunjs",
] as const;

export type SkillIconKey = (typeof SKILL_ICON_KEYS)[number];
