/**
 * Extracts light/dark SVGs via tech-stack-icons StackIcon (MIT) — same output as runtime.
 * Run: bun run extract:stack-icons
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import StackIcon from "tech-stack-icons";

import { rawOwnerData } from "../src/content/owner-data";

const OUT_PATH = join(process.cwd(), "src/lib/icons/stack-icons.generated.tsx");

type Variant = "light" | "dark";

function extractRenderedSvg(name: string, variant: Variant): string {
  const html = renderToStaticMarkup(
    createElement(StackIcon, { name, variant }),
  );
  const match = html.match(/<svg[\s\S]*<\/svg>/);
  if (!match) {
    throw new Error(
      `StackIcon did not render an <svg> for "${name}" (${variant})`,
    );
  }
  return match[0];
}

function main() {
  const keys = rawOwnerData.skills.map((s) => s.key);
  const icons: Record<string, { light: string; dark: string }> = {};

  for (const key of keys) {
    try {
      icons[key] = {
        light: extractRenderedSvg(key, "light"),
        dark: extractRenderedSvg(key, "dark"),
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`Failed to extract icon "${key}": ${message}`);
      process.exit(1);
    }
  }

  const keysLiteral = JSON.stringify(keys);
  const iconEntries = keys
    .map((key) => {
      const { light, dark } = icons[key]!;
      return `  ${JSON.stringify(key)}: { light: ${JSON.stringify(light)}, dark: ${JSON.stringify(dark)} }`;
    })
    .join(",\n");

  const output = `/* eslint-disable */
// Auto-generated by scripts/extract-stack-icons.ts — do not edit.
// Source: tech-stack-icons (MIT) — https://tech-stack-icons.com
// Regenerate: bun run extract:stack-icons

export const SKILL_ICON_KEYS = ${keysLiteral} as const;

export type SkillIconKey = (typeof SKILL_ICON_KEYS)[number];

export const STACK_ICONS = {
${iconEntries},
} as const satisfies Record<SkillIconKey, { light: string; dark: string }>;
`;

  writeFileSync(OUT_PATH, output, "utf8");
  console.log(`Wrote ${keys.length} icons to ${OUT_PATH}`);
}

main();
