/**
 * Extracts light/dark SVG subsets from tech-stack-icons (MIT) for owner-data skills.
 * Run: bun run extract:stack-icons
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { rawOwnerData } from "../src/content/owner-data";

const BUNDLE_PATH = join(
  process.cwd(),
  "node_modules/tech-stack-icons/dist/index.js",
);
const OUT_PATH = join(process.cwd(), "src/lib/icons/stack-icons.generated.tsx");

const BLOCK_MARKER = ":{svg:{";

function extractQuotedSvg(block: string, variant: "light" | "dark"): string {
  const marker = `${variant}:'`;
  const vStart = block.indexOf(marker);
  if (vStart < 0) {
    throw new Error(`Missing ${variant} variant in icon block`);
  }

  let i = vStart + marker.length;
  let out = "";
  while (i < block.length) {
    const c = block[i];
    if (c === "\\") {
      out += block[++i];
      i++;
      continue;
    }
    if (c === "'") break;
    out += c;
    i++;
  }

  if (!out.startsWith("<svg")) {
    throw new Error(`Invalid ${variant} SVG (expected <svg opener)`);
  }

  return out;
}

function extractIconBlock(bundle: string, key: string): string {
  const start = bundle.indexOf(`${key}${BLOCK_MARKER}`);
  if (start < 0) {
    throw new Error(`Icon key not found in tech-stack-icons bundle: "${key}"`);
  }

  const next = bundle.indexOf(
    BLOCK_MARKER,
    start + key.length + BLOCK_MARKER.length,
  );
  const end = next > start ? next : start + 120_000;
  return bundle.slice(start, end);
}

function main() {
  let bundle: string;
  try {
    bundle = readFileSync(BUNDLE_PATH, "utf8");
  } catch {
    console.error(
      `Could not read ${BUNDLE_PATH}. Run "bun install" (tech-stack-icons is a devDependency).`,
    );
    process.exit(1);
  }

  const keys = rawOwnerData.skills.map((s) => s.key);
  const icons: Record<string, { light: string; dark: string }> = {};

  for (const key of keys) {
    const block = extractIconBlock(bundle, key);
    const light = extractQuotedSvg(block, "light");
    const dark = extractQuotedSvg(block, "dark");
    icons[key] = { light, dark };
  }

  const keysLiteral = JSON.stringify(keys);
  const iconEntries = keys
    .map((key) => {
      const { light, dark } = icons[key]!;
      return `  ${JSON.stringify(key)}: { light: ${JSON.stringify(light)}, dark: ${JSON.stringify(dark)} }`;
    })
    .join(",\n");

  const output = `/* eslint-disable */
// Auto-generated by scripts/extract-stack-icons.ts — do not edit.
// Source: tech-stack-icons (MIT) — https://tech-stack-icons.com
// Regenerate: bun run extract:stack-icons

export const SKILL_ICON_KEYS = ${keysLiteral} as const;

export type SkillIconKey = (typeof SKILL_ICON_KEYS)[number];

export const STACK_ICONS = {
${iconEntries},
} as const satisfies Record<SkillIconKey, { light: string; dark: string }>;
`;

  writeFileSync(OUT_PATH, output, "utf8");
  console.log(`Wrote ${keys.length} icons to ${OUT_PATH}`);
}

main();
