/**
 * Extracts light/dark SVGs via tech-stack-icons StackIcon (MIT).
 * Run: bun run extract:stack-icons
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import StackIcon from "tech-stack-icons";

import { rawOwnerData } from "../src/content/owner-data";

const ICONS_DIR = join(process.cwd(), "public/icons");
const KEYS_PATH = join(process.cwd(), "src/lib/icons/stack-icon-keys.ts");

type Variant = "light" | "dark";

function extractRenderedSvg(name: string, variant: Variant): string {
  const html = renderToStaticMarkup(
    createElement(StackIcon, { name, variant }),
  );
  const match = html.match(/<svg[\s\S]*<\/svg>/);
  if (!match) {
    throw new Error(
      `StackIcon did not render an <svg> for "${name}" (${variant})`,
    );
  }
  return match[0];
}

function main() {
  const keys = rawOwnerData.skills.map((s) => s.key);
  mkdirSync(ICONS_DIR, { recursive: true });

  let fileCount = 0;

  for (const key of keys) {
    try {
      for (const variant of ["light", "dark"] as const) {
        const svg = extractRenderedSvg(key, variant);
        const filePath = join(ICONS_DIR, `${key}-${variant}.svg`);
        writeFileSync(filePath, svg, "utf8");
        fileCount++;
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`Failed to extract icon "${key}": ${message}`);
      process.exit(1);
    }
  }

  const keysLiteral = JSON.stringify(keys);
  const manifest = `// Auto-generated by scripts/extract-stack-icons.ts — do not edit.
// Source: tech-stack-icons (MIT) — https://tech-stack-icons.com
// Regenerate: bun run extract:stack-icons

export const SKILL_ICON_KEYS = ${keysLiteral} as const;

export type SkillIconKey = (typeof SKILL_ICON_KEYS)[number];
`;

  writeFileSync(KEYS_PATH, manifest, "utf8");
  console.log(`Wrote ${fileCount} SVGs to ${ICONS_DIR}`);
  console.log(`Wrote key manifest to ${KEYS_PATH}`);
}

main();
